version: '3.9'
services:
  nginx-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    # ports:
    #   - '${PORT}:${PORT}'
    expose:
    - ${PORT}
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST} # the incomming domain name for this site
      VIRTUAL_PORT: ${PORT} # the port your applicatio
      LETSENCRYPT_HOST: ${VIRTUAL_HOST} # the domain name to issue cert to
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} #
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    external:
      name: nginx-proxy
